version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://doubtsharedb:5432/doubtshare
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://mongoUser:mongoPassword@logdb:27017/doubtshare?authSource=admin
    depends_on:
      - doubtsharedb
      - logdb
    networks:
      - app-network
    container_name: spring-boot-app

  doubtsharedb:
    image: postgres:latest
    environment:
      POSTGRES_DB: doubtshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network
    container_name: doubtsharedb

  logdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    ports:
      - "27017:27017"
    networks:
      - app-network
    container_name: logdb

networks:
  app-network:
    driver: bridge
